version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Persist data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_alerts_development
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/app
      - ./config/master.key:/app/config/master.key  # Add this line
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/crypto_alerts_development
      - REDIS_URL=redis://redis:6379/0
    stdin_open: true
    tty: true

volumes:
  db_data:
